pratt.c: added subexpr_kind node
the reasoning behind this new node is because i realized that
later i need to implement semantic analyzer, one of example
where subexpr_kind useful is to detect nested relational operators:

    a > b > c

the above expression doesn't have the same semantic as how it's work
in math:

    a > b && a > c

thus a warning or error is useful.

this is how gcc handles it, it gives a useful warning:

      test.c: In function ‘main’:
      test.c:2:16: warning: comparisons like ‘X<=Y<=Z’ do not have their mathematical meaning [-Wparentheses]

and in rust, it's an error:

      error: comparison operators cannot be chained
       --> src/main.rs:2:7
        |
      2 |     1 < 2 < 3;
        |       ^   ^
        |
      help: split the comparison into two
        |
      2 |     1 < 2 && 2 < 3;
        |           ++++